    // 大規模実行画面と1試合実行画面で共通の打順入力フォーム。画面固有スクリプトより先に読み込み、画面側でstartLineupFormを呼び出す。
    type Personality = 'DEFAULT' | 'MIDDLE_DISTANCE' | 'EAGER_SLUGGISH' | 'HIGH_ON_BASE' | 'EAGER_STEAL' | 'EAGER_BUNT';
    interface LineupPlayer { hitAverage: string; buntEnabled: boolean; stealEnabled: boolean; personality: Personality; buntForced?: boolean; stealForced?: boolean; memo?: string; }
    interface LineupField { key: 'hitAverage'; label: string; min: number; max: number; }
    interface LineupRequestPlayer { hit_average: number; bunt_enabled: boolean; steal_enabled: boolean; personality: Personality; }
    // config: readyMessage(入力完了時の案内), runningMessage(実行中の案内), endpoint(打順の送信先), onSuccess(成功時の応答JSONを描画する関数)
    interface LineupFormConfig<T> { readyMessage: string; runningMessage: string; endpoint: string; onSuccess(data: T): void; }
    const lineup: LineupPlayer[] = [
      {hitAverage:'0.35',buntEnabled:true,stealEnabled:true,personality:'DEFAULT'},
      {hitAverage:'0.35',buntEnabled:true,stealEnabled:true,personality:'DEFAULT'},
      {hitAverage:'0.35',buntEnabled:false,stealEnabled:false,personality:'DEFAULT'},
      {hitAverage:'0.35',buntEnabled:false,stealEnabled:false,personality:'DEFAULT'},
      {hitAverage:'0.35',buntEnabled:false,stealEnabled:false,personality:'DEFAULT'},
      {hitAverage:'0.33',buntEnabled:true,stealEnabled:true,personality:'DEFAULT'},
      {hitAverage:'0.29',buntEnabled:true,stealEnabled:true,personality:'DEFAULT'},
      {hitAverage:'0.28',buntEnabled:true,stealEnabled:true,personality:'DEFAULT'},
      {hitAverage:'0.27',buntEnabled:true,stealEnabled:true,personality:'DEFAULT'}
    ];
    let inFlight = false;
    let hasResults = false;
    let lineupFormConfig: LineupFormConfig<unknown>;
    const order = document.querySelector<HTMLDivElement>('#order')!, submit = document.querySelector<HTMLButtonElement>('#submit')!, feedback = document.querySelector<HTMLElement>('#feedback')!, toggleAllBunt = document.querySelector<HTMLButtonElement>('#toggle-all-bunt')!, toggleAllSteal = document.querySelector<HTMLButtonElement>('#toggle-all-steal')!, resetAllPersonalities = document.querySelector<HTMLButtonElement>('#reset-all-personalities'), teamSelect = document.querySelector<HTMLSelectElement>('#team-select'), averageDisplay = document.querySelector<HTMLElement>('#average-hit-average'), inputView = document.querySelector<HTMLElement>('#input-view')!, resultsView = document.querySelector<HTMLElement>('#results')!, tabInput = document.querySelector<HTMLButtonElement>('#tab-input')!, tabResults = document.querySelector<HTMLButtonElement>('#tab-results')!, editLineup = document.querySelector<HTMLButtonElement>('#edit-lineup')!, resultFeedback = document.querySelector<HTMLElement>('#result-feedback')!;
    const ranges = {hitAverage:[0.01,0.6]} satisfies Record<LineupField['key'], [number, number]>;
    function valid(player: Pick<LineupPlayer, 'hitAverage'>): boolean { return Object.entries(ranges).every(([key,[min,max]]) => player[key as LineupField['key']] !== '' && Number(player[key as LineupField['key']]) >= min && Number(player[key as LineupField['key']]) <= max); }
    function validLineup(): boolean { return lineup.every(valid); }
    const fields: LineupField[] = [{key:'hitAverage',label:'打率',min:0.01,max:0.6}];
    function toggle(label: string, enabled: boolean, onClick: () => void): HTMLButtonElement { const button=document.createElement('button'); button.type='button'; button.className='bunt-toggle'; button.disabled=inFlight; const caption=document.createElement('span'); caption.className='toggle-label'; caption.textContent=`${label}:`; const state=document.createElement('span'); state.className='toggle-state'; state.textContent=enabled?'する':'しない'; button.append(caption, state); button.setAttribute('aria-label',`${label}: ${enabled?'する':'しない'}`); button.setAttribute('aria-pressed',String(enabled)); button.addEventListener('click',onClick); return button; }
    function averageHitAverage(players: Pick<LineupPlayer, 'hitAverage'>[]): string { if (!players.every(valid)) return '—'; return (players.reduce((sum,player)=>sum+Number(player.hitAverage),0)/players.length).toFixed(3); }
    function lineupRequest(players: LineupPlayer[]): LineupRequestPlayer[] { return players.map(player=>({hit_average:Number(player.hitAverage),bunt_enabled:player.buntEnabled,steal_enabled:player.stealEnabled,personality:player.personality})); }
    function parseDefaultBatters(elements: Iterable<{dataset: DOMStringMap}>): LineupPlayer[] { return Array.from(elements, element=>{const data=element.dataset; const stealForced=data.stealForced==='true', buntForced=data.buntForced==='true'; return {hitAverage:data.hitAverage!,personality:data.personality as Personality,stealForced,buntForced,stealEnabled:stealForced,buntEnabled:buntForced,memo:''};}); }
    function applyTeam(key: string): void { const team=document.querySelector(`#team-defaults [data-team="${key}"]`); if (!team) return; lineup.splice(0,lineup.length,...parseDefaultBatters(team.querySelectorAll<HTMLElement>('[data-batter]'))); }
    function formatPercentage(value: string): string { return value === '' ? value : Number(value).toFixed(2); }
    const personalityLabels = {DEFAULT:'単打マン',MIDDLE_DISTANCE:'中距離砲',EAGER_SLUGGISH:'長距離砲',HIGH_ON_BASE:'高出塁率',EAGER_STEAL:'盗塁重視',EAGER_BUNT:'バント職人'} satisfies Record<Personality, string>;
    function fieldWrapper(caption: string, control: HTMLElement, extraClass?: string): HTMLLabelElement { const wrapper=document.createElement('label'); wrapper.className=extraClass ? `field ${extraClass}` : 'field'; const label=document.createElement('span'); label.className='eyebrow field-caption'; label.textContent=caption; wrapper.append(label, control); return wrapper; }
    function personalitySelect(player: LineupPlayer): HTMLSelectElement { const select=document.createElement('select'); select.disabled=inFlight; Object.entries(personalityLabels).forEach(([value,label])=>{const option=document.createElement('option');option.value=value;option.textContent=label;option.selected=player.personality===value;select.append(option);}); select.addEventListener('change',()=>{player.personality=select.value as Personality;}); return select; }
    // 打順組み替え画面（data-lineup-mode="reorder"）では、打率をラベル表示にして打者のドラッグで打順を入れ替える。
    const reorderMode = order.dataset.lineupMode === 'reorder';
    if (reorderMode && teamSelect) applyTeam(teamSelect.value);
    let dragIndex: number | null = null;
    function movePlayer<T>(players: T[], from: number, to: number): boolean { if (from === to || to < 0 || to >= players.length) return false; const [moved]=players.splice(from,1); players.splice(to,0,moved); return true; }
    function forcedLabel(label: string): HTMLSpanElement { const wrapper=document.createElement('span'); wrapper.className='forced-label'; const caption=document.createElement('span'); caption.className='toggle-label'; caption.textContent=`${label}:`; const state=document.createElement('span'); state.className='toggle-state'; state.textContent='する'; wrapper.append(caption, state); wrapper.setAttribute('aria-label',`${label}: する（固定）`); return wrapper; }
    function memoInput(player: LineupPlayer, index: number): HTMLInputElement { const input=document.createElement('input'); input.type='text'; input.className='memo-input'; input.maxLength=20; input.value=player.memo||''; input.disabled=inFlight; input.setAttribute('aria-label',`${index+1}番のメモ`); input.addEventListener('input',()=>{player.memo=input.value;}); return input; }
    function statLabel(value: string): HTMLSpanElement { const label=document.createElement('span'); label.className='stat-value'; label.textContent=value; return label; }
    function slotIndexAt(x: number, y: number): number | null { const slot=document.elementFromPoint(x,y)?.closest<HTMLElement>('.slot'); return slot && order.contains(slot) ? Number(slot.dataset.index) : null; }
    function clearDragState(): void { order.querySelectorAll('.dragging, .drop-target').forEach(slot=>slot.classList.remove('dragging','drop-target')); }
    function dragHandle(row: HTMLDivElement, index: number): HTMLButtonElement { const handle=document.createElement('button'); handle.type='button'; handle.className='drag-handle'; handle.disabled=inFlight; handle.textContent='⠿'; handle.setAttribute('aria-label',`${index+1}番の打者を移動（ドラッグまたは上下キー）`); handle.addEventListener('pointerdown',event=>{if(inFlight)return; event.preventDefault(); dragIndex=index; handle.setPointerCapture(event.pointerId); row.classList.add('dragging');}); handle.addEventListener('pointermove',event=>{if(dragIndex===null)return; order.querySelectorAll('.drop-target').forEach(slot=>slot.classList.remove('drop-target')); const target=slotIndexAt(event.clientX,event.clientY); if(target!==null&&target!==dragIndex)order.children[target].classList.add('drop-target');}); handle.addEventListener('pointerup',event=>{if(dragIndex===null)return; const from=dragIndex; dragIndex=null; const target=slotIndexAt(event.clientX,event.clientY); if(target!==null&&movePlayer(lineup,from,target)){render();}else{clearDragState();}}); handle.addEventListener('pointercancel',()=>{dragIndex=null; clearDragState();}); handle.addEventListener('keydown',event=>{const offset=({ArrowUp:-1,ArrowDown:1} as Record<string, number>)[event.key]; if(offset===undefined||inFlight)return; event.preventDefault(); if(movePlayer(lineup,index,index+offset)){render(); order.children[index+offset].querySelector<HTMLButtonElement>('.drag-handle')!.focus();}}); return handle; }
    function render(): void { order.replaceChildren(); lineup.forEach((player,index) => { const row=document.createElement('div'); row.className='slot'; row.dataset.index=String(index); const position=document.createElement('span'); position.className='slot-index'; position.textContent=`${index+1}番`; row.append(position); if (reorderMode) row.append(dragHandle(row,index)); fields.forEach(field => { if (reorderMode) { row.append(fieldWrapper(field.label, statLabel(player[field.key]))); return; } const input=document.createElement('input'); input.type='number'; input.required=true; input.min=String(field.min); input.max=String(field.max); input.step='0.01'; input.value=player[field.key]; input.disabled=inFlight; input.addEventListener('input',()=>{const value=input.value.startsWith('.') ? `0${input.value}` : input.value;input.value=value;player[field.key]=value;update();}); input.addEventListener('change',()=>{const value=formatPercentage(input.value);input.value=value;player[field.key]=value;update();}); row.append(fieldWrapper(field.label, input)); }); const personalityControl=reorderMode ? statLabel(personalityLabels[player.personality]) : personalitySelect(player); const buntControl=player.buntForced ? forcedLabel('バント') : toggle('バント',player.buntEnabled,()=>{player.buntEnabled=!player.buntEnabled; render();}); const stealControl=player.stealForced ? forcedLabel('盗塁') : toggle('盗塁',player.stealEnabled,()=>{player.stealEnabled=!player.stealEnabled; render();}); row.append(fieldWrapper('性格', personalityControl, 'field-personality'), buntControl, stealControl); if (reorderMode) row.append(fieldWrapper('メモ', memoInput(player,index))); order.append(row); }); update(); }
    function update(): void { const complete=validLineup(); const allBuntEnabled=lineup.filter(player=>!player.buntForced).every(player=>player.buntEnabled); const allStealEnabled=lineup.filter(player=>!player.stealForced).every(player=>player.stealEnabled); if (averageDisplay) averageDisplay.textContent=averageHitAverage(lineup); if (teamSelect) teamSelect.disabled=inFlight; submit.disabled=inFlight || !complete; toggleAllBunt.disabled=inFlight; toggleAllBunt.setAttribute('aria-pressed',String(allBuntEnabled)); toggleAllSteal.disabled=inFlight; toggleAllSteal.setAttribute('aria-pressed',String(allStealEnabled)); if (resetAllPersonalities) resetAllPersonalities.disabled=inFlight; tabInput.disabled=inFlight; tabResults.disabled=inFlight || !hasResults; editLineup.disabled=inFlight; if (!inFlight) { feedback.className=''; feedback.textContent=complete?lineupFormConfig.readyMessage:'打率は0.01〜0.6の範囲ですべての項目を入力してください。'; } }
    function showView(resultsVisible: boolean): void { inputView.hidden=resultsVisible; resultsView.hidden=!resultsVisible; tabInput.setAttribute('aria-selected',String(!resultsVisible)); tabResults.setAttribute('aria-selected',String(resultsVisible)); update(); window.scrollTo({top:0}); }
    function startLineupForm<T>(config: LineupFormConfig<T>): void {
      lineupFormConfig=config;
      tabInput.addEventListener('click',()=>showView(false));
      tabResults.addEventListener('click',()=>showView(true));
      editLineup.addEventListener('click',()=>showView(false));
      toggleAllBunt.addEventListener('click',()=>{const targets=lineup.filter(player=>!player.buntForced);const enabled=!targets.every(player=>player.buntEnabled);targets.forEach(player=>{player.buntEnabled=enabled;});render();});
      toggleAllSteal.addEventListener('click',()=>{const targets=lineup.filter(player=>!player.stealForced);const enabled=!targets.every(player=>player.stealEnabled);targets.forEach(player=>{player.stealEnabled=enabled;});render();});
      if (teamSelect) teamSelect.addEventListener('change',()=>{applyTeam(teamSelect.value);render();});
      if (resetAllPersonalities) resetAllPersonalities.addEventListener('click',()=>{lineup.forEach(player=>{player.personality='DEFAULT';});render();});
      submit.addEventListener('click',async()=>{if(inFlight||!validLineup())return; inFlight=true;render();feedback.className='';feedback.textContent=lineupFormConfig.runningMessage;try {const response=await fetch(lineupFormConfig.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lineupRequest(lineup))});const data=await response.json();if(!response.ok)throw new Error(data.error||data.message||'リクエストに失敗しました。');lineupFormConfig.onSuccess(data);hasResults=true;showView(true);}catch(error){feedback.className='error';feedback.textContent=error instanceof Error ? error.message : String(error);}finally{inFlight=false;render();}});
      render();
    }
