plugins {
    id 'com.diffplug.spotless' version '8.2.1' apply false
}

allprojects {
    group = 'com.example.baseballorders'
    version = '0.1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'com.diffplug.spotless'
    spotless {
        java {
            googleJavaFormat().aosp()
            removeUnusedImports()
            trimTrailingWhitespace()
            endWithNewline()
        }
    }
    plugins.withType(JavaPlugin).configureEach {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(25)
            }
        }

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
    }
}

tasks.register('build') {
    group = 'build'
    dependsOn subprojects.collect { it.tasks.named('build') }
}

tasks.register('clean') {
    group = 'build'
    dependsOn subprojects.collect { it.tasks.named('clean') }
}
