simulation:
  game-count: 10
  sqs:
    poll-fixed-delay: ${SIMULATION_SQS_POLL_FIXED_DELAY:60s}
    request-queue-name: ${SIMULATION_REQUEST_QUEUE_NAME:simulation-request}
    result-queue-name: ${SIMULATION_RESULT_QUEUE_NAME:simulation-result}
