simulation:
  game-count: 100
  sqs:
    max-messages-per-poll: 10
    long-poll-seconds: 10
    poll-fixed-delay: ${SIMULATION_SQS_POLL_FIXED_DELAY:60s}
  rule:
    batting:
      walk-probability: 0.05
      strikeout-probability-when-not-on-base: 0.25
    middle-distance-hitting:
      double-divisor: 6
      triple-divisor: 6
      home-run-divisor: 6
      single-reduction-divisor: 2
    long-distance-hitting:
      double-divisor: 8
      triple-divisor: 8
      home-run-divisor: 2
      single-reduction-divisor: 1
    standard-steal:
      to-double-attempt-rate: 0.2
      to-triple-attempt-rate: 0.05
    eager-steal:
      to-double-attempt-rate: 0.3
      to-triple-attempt-rate: 0.15
    runner-advance:
      from-first-probability: 0.2
      from-second-probability: 0.2
      from-third-probability: 0.1
  pitcher:
    bold:
      on-base-multiplier: 1.3
      slugging-multiplier: 0.7
      running-multiplier: 1.0
    cautious:
      on-base-multiplier: 0.7
      slugging-multiplier: 1.0
      running-multiplier: 1.3
    technical:
      on-base-multiplier: 1.0
      slugging-multiplier: 1.3
      running-multiplier: 0.7
    standard:
      on-base-multiplier: 1.0
      slugging-multiplier: 1.0
      running-multiplier: 1.0
