spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:baseball-orders;DB_CLOSE_DELAY=-1}
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  sql:
    init:
      mode: always

baseball-orders:
  simulation:
    result-timeout: 30s
    maximum-average-hit-average: 0.35
  rendering:
    single-game:
      frame-duration-millis: 1000
      hit-frame-duration-millis: 1800
      score-frame-duration-millis: 2200
      home-run-frame-duration-millis: 3600
      bunt-frame-duration-millis: 1600
