spring.cloud.aws.sqs.listener.auto-startup: false

baseball-orders:
  simulation:
    result-timeout: 30s
    maximum-average-hit-average: 0.35
  rendering:
    single-game:
      frame-duration-millis: 1000
      hit-frame-duration-millis: 1800
      score-frame-duration-millis: 2200
      home-run-frame-duration-millis: 3600
      bunt-frame-duration-millis: 1600
