spring:
  profiles:
    default: local
  application:
    name: baseball-orders-backend

baseball-orders:
  simulation:
    result-timeout: ${SIMULATION_RESULT_TIMEOUT:30s}
    maximum-average-hit-average: ${SIMULATION_MAXIMUM_AVERAGE_HIT_AVERAGE:0.35}
    maximum-average-sluggish: ${SIMULATION_MAXIMUM_AVERAGE_SLUGGISH:0.4}
  rendering:
    single-game:
      frame-duration-millis: ${SINGLE_GAME_FRAME_DURATION_MILLIS:1000}
spring.cloud.aws:
  region:
    static: ap-northeast-1

simulation:
  sqs:
    request-queue-name: ${SIMULATION_REQUEST_QUEUE_NAME:simulation-request}
    result-queue-name: ${SIMULATION_RESULT_QUEUE_NAME:simulation-result}

logging:
  level:
    com.example.baseballorders.backend: INFO
