server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict

baseball-orders:
  simulation:
    result-timeout: 30s
    maximum-average-hit-average: 0.35
    maximum-average-sluggish: 0.4
    pitcher-increase-multiplier: 1.3
    maximum-success-rate: 0.7
  security:
    local-account:
      minimum-password-length: 12
