CREATE TABLE simulations (
    simulation_id UUID PRIMARY KEY,
    user_id BIGINT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP NULL,
    CONSTRAINT fk_simulations_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE simulation_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulation_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    average_score DOUBLE PRECISION NOT NULL,
    median_score DOUBLE PRECISION NOT NULL,
    maximum_score INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_simulation_statistics_simulation FOREIGN KEY (simulation_id) REFERENCES simulations (simulation_id),
    CONSTRAINT fk_simulation_statistics_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_simulation_statistics_simulation UNIQUE (simulation_id)
);
